name: DigitalOcean

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Build image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        port: ${{ secrets.DO_PORT }}
        script: |
         cd ./api
         ./update.sh
         ./build.sh
         
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        port: ${{ secrets.DO_PORT }}
        script: |
         cd ./api
         ./deploy.sh
 
       
