name: DigitalOcean

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Run build script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        PORT: ${{ secrets.DO_PORT }}
        KEY: ${{ secrets.DO_SSHKEY }}
        script: build.sh
       
